# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    docker:
      - image: ruby:2.6.10
    steps:
      - checkout
      - run:
          name: Install Bundler 1.17.2
          command: |
            gem install bundler -v 1.17.2
            bundle _1.17.2_ install --jobs 4 --retry 3
      - run:
          name: Run Fastlane Tests
          command: bundle exec fastlane upload_app

workflows:
  try-workflow:
    jobs:
      - try-job

# # .circleci/config.yml
# version: 2.1
# jobs:
#   try-job:
#     macos:
#       xcode: 15.2.0
#     steps:
#       - run: echo "i am a job named try job within a workflow named try-workflow"

# workflows:
#   try-workflow:
#     jobs:
#       - try-job