# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    docker:
      - image: ruby:2.6.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAEwQeUkM
ZBxW1F/vbJ3x8LAAAAGAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDObJq39Fit
yXSOJwZeh14UTQgAMC5IbgLZZ22SCGWYtYBswrHGm0lGFPsVDD9C4sIQZqQXTijIs4wAkj
p0UPKoSPydoQc8g9y8OlOYArbL41klzF1llMNO2PhD53ozOaXNuMKEpsuazxxjrG/yIzob
7x4E189I6sN96QzvdgaI73p6byV0uPXqNKtAcM+j09myYSD+Yz87joyrCD60DwxAvPbOyH
g/8R/fQWlSGQbTFLYEx5BHjz3ItzLl0HUHtO6CFNad08lU07o4la+NR/WNW58SA5KS60mY
lt4u0ybxf7ymT9L3PL33Zhtv3ZYV0sTwSjnYs057Lf+JN5Kxm1oFAPKPf6gUsTgASDEE/Z
0Q7VwHu6c0Uj3cpybMBi2IOTS8YdDvl/zpkWLu4k4CqB7z1v4/zGjF75PZiXCWEY7uUMON
X+cqVz04UCPa9iUrjUBdzrm9rLF2PZoEluyPosd/OkwCGwsrqCoSy1R6H2YQmiZ2QR9fCn
wLXndh39Ur7O+of36VtOVIiA8oR/4eKV/X37aHvM28oIysi2tZ4Ljzw1/WhRdbU/STIPPc
3gRIK3k1Yguaqp9U/8jex2vc1cOcsOOEaMCubq1SbFc4+Y24mYVI3fRwtXMKmSQ5lcLYYl
SGu9n7b4+TdKf4npKNzkFvuOHgjG8PGhpyxlw9SXeduQAAB1BW3UkV1+0fhKjg4uSjb5D4
dfr7e0ASy7rwSBZwXNGLXUZTJXeyQBn5dAcdvwsAfVCL7zN183QRDfJI2nR5Gt6eP2JXv6
wNTaOW98F4KLaNQyJpANZ6idQnUwPMWbsJPFkj6zT+uwQn6G2LV+BQzNfqA1UKIbxv3G6m
9wxq/GSyJltyAmL5uprCAgWtssYPCp7ZlRqwM11dLuRRD5dZT+S/LfVG7meJKSgGM+pFpT
Tn0i5E7wMUkw4IUB76sOKz2e0Y04lF0pp1ocQX6Avu2P+lMLRuLeB153CUiSZXKEDUWPfL
SknJtuVmo2zuPP0DvkaiND1/TQ1TUEirCMii/TCTFG43O1smhTRGtmPjgeO6Vbbs3INWL8
bvf8wsiix5ALlTHbHVQUxg0iHFWlBPu/uxyqCF2f3JSp3fd7eelsRYZRtDXxYrI57L5Bko
aTj6k/Q+9T9d3To4OzzIsjlby7FO+B0vUUEEiCGKHhNajIxU7T/m8kZPLgjljY8QjB2/xY
32jIkutXg5crSQV8byhWku14TOGp3DTjYdxtMJ/I/Hk4jr0tJUjWQTmTGExv5TSmPvgRfd
XlRiKiAxOc3TDbojfnLzP3F0Fz3tlz9AXK1BxjVYKJTpelQ3RaWrXSjlIrP3NP913jCUef
rsaeHbXguRyMZOyMhmxPmJnt4AO+Tu3aicBQOtAn84b0G6AwhipplhrwZxAyYWC8md2kon
33reDda3WksaGBwsPs30VEIFQVzpndPuYivfjmJIyFQZXgPht7ipVPFtBfTqMj8U3nRuf4
4TWLLFFOTLDjuPs//614rpvCxzGh3yCY8euRS388/1vYtCvd9rAEC8r8POZCY59cuaP+3l
OCzl13ptQ5PjQEUwVBjTyR2M7lUQCwaOMCfMzAAHOTWU+fVU+Ug5/y9qEAg1gS5ZfTSwTX
FClsJ+Gka5Sfsb00ztt5MHZKn2et1qGXl5KARDSIOnTC+Jtum3mXpfdaVEE4OIoicDjZ/a
Hs1VL29lOOCG2LJWXi2CW0WipPXMhZWUXIPkzaJZgsoHDW3qVL8TeZwjbsgkaoYS+cInCn
MPh7EiFbEu2mFDG+mnQHZYf3d8BhNcT9zLMMkS78SgEDZ5EcYg4zEGUqCkO+6witEYbh0S
IK0jlRo69gaA6vG4SDpxDEAYeoOpgQ+AR3S3JKEK8Od7eNrO2TOmBqUNB2tmkV5xsU8r5C
VwXt3FgoQLytq/wiCOZqpPqOA8z4lyoOlgf52E9Ou0QmMO75C1xr3Lxe4wXHppvrPZ/Oj4
nL2LbvC+Df5xqUbbLORDcbR302ycuUnNfbjeKKJ8LJP8gYREzf75Ayqr5TAGFSNyK6tSEX
klX+6k0BWaNXe6Ds5ShoYjzlzk9V7WsAZNaHR9VVckh7WTuWeQi6+V4TEtixYU6uI9ZxZs
8Gz1VLduqW3VCKVQnsxTvoXj8swy0ndCXfPx3h2tpzyy0Aqm8npiB6cEvfxE7vMkIjDqpx
YK19zI7Rf5HWZGM5otZgDdGWn+u+DVmLsdlhlI5xNrr9gx/XzEt2rl+wAQAkrr1+FLNg8E
VKv+d747Cwdz+xAfgLCHK80haBa8a6FeTv0JaOpn4Fman72eICUDjbRYpEjxIEXfqedP1r
KvyaMLgHTZcrF4eL6x7XZ9iInJ/W0pfw/jfh4Zp+FSFCULhEQlKKjQF7nNgE5wns14YLeu
ggC0qXfsvXPyB9mHmIIdW+kCoElmbCIrCXQviSynMs8HoNuxOQ+Z36XcQiwbrNyqnDRIMo
o7DpF43fDn1NQ/0H+vn+M5atAZoHx20TzUH2p2wsWeLq0uORd77zAQYyAL+ccNJGxpACbX
fS6/Vjz9bUM881abENl5l63nTPS6i8eGWdF699EJihiu16KfMrXd4mlS0PkDNh6fmyQ1+4
iuRxfqHoguZNZOSIEFsx6NY61XJ9sj99BocHf6TCbT3r58A8KDgCGwc3IUF9pD/lCjTBqh
/scqi8KEzupihP5tLRBe7eaEQZrUuxg4Ufed1hM/ac47on1Q8oE+rVJEsdH7mU320xj8Pq
iXvuvt+8JE8ZGSBr22XDieUostDnHVY8jI9hUfu3iJv07g/cAo4diPvBWqrbmvr1Ao/ZiE
mV+2sg3BUCL78I+UbZZVHm+8BFMRGM4OtndvP9IeH6dBJTbD8nTRiyxAdmZ5kOchgkIAkX
SWgZ+06p1H8LzlOXhnjSoIGOs4bV1QsXB8zRO3UzO2Uv1xM5uqKaZajlLiSfnOD+RFoOKa
ESTWx+ot5PwDmfIX/8ZwNijJP6vXmy2S7z0peQ5j+gsT7qfrIP2QSqzT5nzDMbJwkJJw4a
kEuGAmMi8m0yUYQhMj4P7L5kFRHtg6pV8aAVURQjLXfV5u3lfj0kWHZ8lSCIQqsrAAhsiT
MbZiVs0pUb15kUcyL2q1fs/is7kivaT5C97g8Cwk+kJeNX1uoGqecceGzh+1q6huFXYXti
S9ODjWSCnJIqfh0kpDAS40SW8="  # Replace with your SSH fingerprint
      - run:
          name: Install Bundler 1.17.2
          command: |
            gem install bundler -v 1.17.2
            bundle install
      - run:
          name: Run Fastlane Archive the app
          command: bundle exec fastlane buildApp_localy

workflows:
  try-workflow:
    jobs:
      - try-job


#bundle _1.17.2_ install --jobs 4 --retry 3

# # .circleci/config.yml
# version: 2.1
# jobs:
#   try-job:
#     macos:
#       xcode: 15.2.0
#     steps:
#       - run: echo "i am a job named try job within a workflow named try-workflow"

# workflows:
#   try-workflow:
#     jobs:
#       - try-job