# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - run:
          name: Install rbenv and required Ruby version
          command: |
            brew install rbenv
            rbenv init
            rbenv install 2.6.10
            rbenv global 2.6.10
            echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
            source ~/.bash_profile
      - run:
          name: Set up Git credentials
          command: |
            git config --global url."https://${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}@github.com/".insteadOf "https://github.com/"
      - run:
          name: Install Bundler 1.17.2
          command: |
            gem install bundler -v 1.17.2
            bundle install
      - run:
          name: Install rbenv and required Ruby version
          command: |
            brew install rbenv
            rbenv init
            rbenv install $RUBY_VERSION
            rbenv global $RUBY_VERSION
            echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
            source ~/.bash_profile

      - run:
          name: Install Bundler and CocoaPods
          command: |
            gem install bundler -v 1.17.2
            gem install cocoapods

      - run:
          name: Install dependencies
          command: |
            bundle install
            bundle exec pod install

      - run:
          name: Run Fastlane Archive the app
          command: bundle exec fastlane buildApp_localy

workflows:
  try-workflow:
    jobs:
      - try-job


#bundle _1.17.2_ install --jobs 4 --retry 3

# # .circleci/config.yml
# version: 2.1
# jobs:
#   try-job:
#     macos:
#       xcode: 15.2.0
#     steps:
#       - run: echo "i am a job named try job within a workflow named try-workflow"

# workflows:
#   try-workflow:
#     jobs:
#       - try-job