# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    docker:
      - image: ruby:2.6.10
    steps:
      - checkout
      - run:
          name: Install Bundler and dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Run Fastlane Tests
          command: bundle exec fastlane upload_app

workflows:
  try-workflow:
    jobs:
      - try-job

## .circleci/config.yml
# version: 2.1
# jobs:
#   try-job:
#     macos:
#       xcode: 15.2.0
#     steps:
#     - checkout
#       - run: echo "i am a job named try job within a workflow named try-workflow"

#       - run:
#           name: Run Fastlane Tests
#           command: bundle exec fastlane upload_app

# workflows:
#   try-workflow:
#     jobs:
#       - try-job