# .circleci/config.yml
version: 2.1
jobs:
  build:
    macos:
      xcode: "15.2.0"
    environment:
      RUBY_VERSION: "2.6.10"
    steps:
      - checkout

      - run:
          name: Initialize rbenv
          command: eval "$(rbenv init -)"

      - run:
          name: Set Ruby version
          command: rbenv global $RUBY_VERSION

      - run:
          name: Verify Ruby version
          command: ruby -v

      - run:
          name: Install Bundler and CocoaPods
          command: |
            gem install bundler -v 1.17.2
            gem install cocoapods

      - run:
          name: Install dependencies
          command: |
            bundle install
            bundle exec pod install

      - run:
          name: Run Fastlane to Build the App
          command: bundle exec fastlane buildApp_localy

workflows:
  try-workflow:
    jobs:
      - try-job


#bundle _1.17.2_ install --jobs 4 --retry 3

# # .circleci/config.yml
# version: 2.1
# jobs:
#   try-job:
#     macos:
#       xcode: 15.2.0
#     steps:
#       - run: echo "i am a job named try job within a workflow named try-workflow"

# workflows:
#   try-workflow:
#     jobs:
#       - try-job