# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    macos:
      xcode: 15.2.0
    steps:
      - run: echo "i am a job named try job within a workflow named try-workflow"

workflows:
  try-workflow:
    jobs:
      - try-job